# Generated by Django 3.2.4 on 2021-10-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
